### ISSUE TITLE
Uncaught TypeError: $(...).fileupload is not a function

### ISSUE THREAD

**Issue by myitake** [ronnieoverby/blue-imp-upload-aspnet-mvc#1]
Hi, I was trying to get this example running on my machine and I got this error with Chrome.
"Uncaught TypeError: $(...).fileupload is not a function"
I wonder if anyone have got the same error with me. Please offer a solution if you have fixed this issue.
Thank you in advance.

**Comment by ronnieoverby** [comment]
You probably haven't installed the npm dependencies. [Get node/npm](https://nodejs.org/en/) and in the same directory where you find `package.json` run `npm install`.

**Comment by ronnieoverby** [comment]
Included [readme ](https://github.com/ronnieoverby/blue-imp-upload-aspnet-mvc/blob/master/README.md)to talk about this.
